# Basic details
title: "Guys Who Code"
tagline: "Learning to code, one byte at a time."
description: "We are a community working to bridge the gap between people and computer technologies. We also aims at developing on ideas that are useful and beneficial to everyone."
long-description: "GWC is run by a group of tech enthusiastic students and computer science engineers who are really passionate about computer technologies to people."
meta-tags: ["gwc","guys who code","code","learn","technology"]


# Catogories
category-list:

# Tags
tag-list: 

# Includes an icon in the footer for each username you enter
social:
  dribbble: guyswhocode
  email: guyswhocode
  facebook: guyswhocode
  flickr: guyswhocode  
  github: guyswhocode
  instagram: guyswhocode
  linkedin: guyswhocode
  pinterest: guyswhocode
  gplus: guyswhocode
  rss: # just type anything here for a working RSS icon
  twitter: guyswhoc0de
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: guyswhocode

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-92626288-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://guyswhocode.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "https://guyswhocode.github.io"

# Permalink structure
permalink: /:title

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME